# Generated by Django 5.1.3 on 2024-12-03 14:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('1', 'Цветок'), ('2', 'Кактус'), ('3', 'Корнеплод')], max_length=1, null=True, verbose_name='Тип')),
                ('photo', models.ImageField(blank=True, upload_to='main', verbose_name='Первичное фото')),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата')),
                ('status', models.CharField(choices=[('1', 'Стабильно'), ('2', 'Требуется осмотр'), ('3', 'Критическое')], default=('2', 'Требуется осмотр'), max_length=1, verbose_name='Статус')),
                ('photo', models.ImageField(null=True, upload_to='main', verbose_name='Фото')),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.plant', verbose_name='Растение')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
            },
        ),
    ]
