# Generated by Django 5.1.3 on 2024-12-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('1', 'Стабильно'), ('2', 'Требуется осмотр'), ('3', 'Критическое')], default=('1', 'Стабильно'), max_length=1, verbose_name='Статус'),
        ),
    ]
