# Generated by Django 5.1.3 on 2024-12-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='humidity',
            field=models.IntegerField(default=35, verbose_name='Влажность (в %)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Стабильно'), ('2', 'Требуется осмотр'), ('3', 'Критическое')], max_length=1, verbose_name='Статус'),
        ),
    ]
